name: dependabot

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: use nodejs v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: setup repository
        run: npm install

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build
